# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v6.1.3
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ''
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ''
odoo_dbfilter: ^prod
odoo_initial_lang: es_ES
odoo_listdb: false
odoo_oci_image: ''
odoo_proxy: traefik
odoo_version: 14.0
paths_without_crawlers:
- /web
- /website/info
postgres_cidr_whitelist: null
postgres_dbname: prod
postgres_exposed: true
postgres_exposed_port: 5432
postgres_username: odoo
postgres_version: '13'
project_author: Galvintec
project_license: OPL-1.0
project_name: tutorial
smtp_default_from: ''
smtp_relay_host: ''

